name: Production Deployment

on:
  push:
    branches: [ main ] # Trigger setiap push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            cd ~/ESP32CAM
            echo "--- UPDATE SOURCE CODE ---"
            git pull origin main

            echo "--- ACTIVATE PYTHON VENV ---"
            source venv/bin/activate

            echo "--- INSTALL PYTHON DEPENDENCIES ---"
            pip install -r server/requirement.txt

            echo "--- START / UPDATE POSTGRESQL ---"
            cd docker
            docker compose up -d

            echo "--- RESTART ESP32CAM SERVICE ---"
            sudo systemctl daemon-reload
            sudo systemctl restart espcam

            echo "--- STATUS SERVICE ---"
            systemctl status espcam --no-pager
            echo "Deploy Berhasil!"
